# Generated by Django 3.0.5 on 2020-05-07 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('translation', models.CharField(max_length=50)),
                ('pronunciation', models.CharField(max_length=50)),
                ('explanation', models.CharField(max_length=100)),
                ('sum_of_like', models.IntegerField(default=0)),
                ('is_show', models.BooleanField(default=False, verbose_name='오늘 표시할 것인가')),
                ('release_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('South Korea', '한국'), ('Japan', '일본'), ('China', '중국')], max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('sum_of_like', models.IntegerField(default=0)),
                ('total_post', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation_name', models.CharField(max_length=100)),
                ('first', models.CharField(max_length=100)),
                ('second', models.CharField(max_length=100)),
                ('third', models.CharField(max_length=100)),
                ('trans_1', models.CharField(default='', max_length=100)),
                ('trans_2', models.CharField(default='', max_length=100)),
                ('trans_3', models.CharField(default='', max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('num_of_like', models.IntegerField(default=0)),
                ('is_trans', models.BooleanField(default=False)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Keyword')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Nation')),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='first_nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='첫번째', to='main.Nation'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='second_nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='두번째', to='main.Nation'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='third_nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='세번째', to='main.Nation'),
        ),
    ]
