# Generated by Django 3.0.5 on 2020-05-02 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('translation', models.CharField(max_length=50)),
                ('pronunciation', models.CharField(max_length=50)),
                ('example_sentence', models.TextField(default='')),
                ('sum_of_like', models.IntegerField(default=0)),
                ('is_show', models.BooleanField(default=False, verbose_name='오늘 표시할 것인가')),
                ('release_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('한국', 'Korea'), ('일본', 'Japan'), ('중국', 'China')], max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('sum_of_like', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100)),
                ('first_translation', models.TextField(null=True)),
                ('second', models.CharField(max_length=100)),
                ('second_translation', models.TextField(null=True)),
                ('third', models.CharField(max_length=100)),
                ('third_translation', models.TextField(null=True)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('num_of_like', models.IntegerField(default=0)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Keyword')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Nation')),
            ],
        ),
    ]
