# Generated by Django 3.0.5 on 2020-05-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='first_nation',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='second_nation',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='third_nation',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
