# Generated by Django 3.0.5 on 2020-05-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200506_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_trans',
            field=models.BooleanField(default=False),
        ),
    ]
