# Generated by Django 3.0.6 on 2020-05-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200511_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='방문자수')),
            ],
        ),
        migrations.AddField(
            model_name='nation',
            name='nation_point',
            field=models.IntegerField(default=0),
        ),
    ]
