# Generated by Django 3.0.5 on 2020-05-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_keyword_example_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='explanation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
