# Generated by Django 3.0.5 on 2020-05-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_keyword_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='first_translation',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='second_translation',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='third_translation',
            field=models.TextField(default='', null=True),
        ),
    ]
