# Generated by Django 3.0.6 on 2020-05-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200521_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='today',
            field=models.BooleanField(default=False, verbose_name='오늘만 보이게 하려면 체크'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='다른 제시어 표시 변수, 건드리지 말자'),
        ),
    ]
