# Generated by Django 3.0.5 on 2020-05-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200502_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='name',
            field=models.CharField(choices=[('Afghanistan', '아프가니스탄'), ('Albania', '알바니아'), ('Algeria', '알제리아'), ('Andorra', '안도라')], max_length=100),
        ),
    ]
