# Generated by Django 3.0.5 on 2020-05-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200503_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nickname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nation',
            name='name',
            field=models.CharField(choices=[('Afghanistan', '아프가니스탄'), ('Albania', '알바니아'), ('Algeria', '알제리아'), ('Andorra', '안도라'), ('Angola', '앙골라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라'), ('Andorra', '안도라')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='first_translation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='second_translation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='third_translation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
