# Generated by Django 3.0.5 on 2020-05-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200503_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first_translation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='second_translation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='third_translation',
            field=models.TextField(blank=True),
        ),
    ]
