# Generated by Django 3.0.5 on 2020-05-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_post_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nation_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
