# Generated by Django 3.0.5 on 2020-05-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_post_nation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='first_translation',
        ),
        migrations.RemoveField(
            model_name='post',
            name='second_translation',
        ),
        migrations.RemoveField(
            model_name='post',
            name='third_translation',
        ),
    ]
